### ISSUE TITLE
how to add acknowledgements

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/hugo-odahub#66]

**Comment by volodymyrss** [comment]
please provide!

**Comment by ferrigno** [comment]
I think it was added

**Comment by volodymyrss** [comment]
@ferrigno if you think it's done, could you refer to commit or doc section so we can track it in the future?

**Comment by ferrigno** [comment]
This is the text online at https://odahub.io/docs/guide-development/ I will not look for the specific commit, too time consuming

The file aknowledgemets.md is used to edit the acknowledgements text, which is shown at the bottom of the products window. The default text refers to the renku repository, in which the workflow was created.

**Comment by volodymyrss** [comment]
It takes less time to find responsible commit than to write your comment. And the links are very helpful since they are the only reliable way to navigate this web graph of issues and documents.
Sorry to hear you were not prepared to do that, @ferrigno .

Here is an advice for you, look into [git blame](https://github.com/oda-hub/hugo-odahub/blame/master/content/docs/guide-development.md) record.

Yet then, it's now integrated in in this issue.

For the record, the change was made in a bulk set of updates in https://github.com/oda-hub/hugo-odahub/pull/67 . It's a bit unfortunate it's like that because it was hard to review such a larger change. It's much better we have incremental updates now.

It's also important to track this to know how we had an issue with a process and have an obvious typo in the doc, which @ferrigno  cited.

In fact, I do not find a reference to `aknowledgemets.md` (or `acknowledgemets.md`) in nb2workflow or oda-bot.   @dsavchenko , do you remember why this could be?

**Comment by dsavchenko** [comment]
> In fact, I do not find a reference to aknowledgemets.md (or acknowledgemets.md) in nb2workflow or oda-bot. @dsavchenko , do you remember why this could be

Here https://github.com/oda-hub/oda-bot/blob/master/odabot%2Fcli.py#L554 for example

**Comment by volodymyrss** [comment]
I add it here https://github.com/oda-hub/hugo-odahub/pull/119 .

I would ask that @ferrigno also re-reads the paragraph to make sure nothing is unclear. I hope we can agree that a typo in the name of the file which is used in specification is potentially problematic. Considering that we have some typos in the core code already which were not yet refactored.
